# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9e1d67608cc49a727ac722dbc1ab545605ac0b169a690cde25823b7ab8398de8c52ec8914b474c6a11e12a433a593e1c4473eab4499b3497f792cfa92fe3a998

test:
  secret_key_base: dc44a4799452bca9c0318ec6172b4bbb78ad5c8ab6505f68436ac6a0fc51d65c247e7dc1f79698ca08ff6aad99437893314ad4adedd23abb3c092326ddfc12e6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
